#!/usr/bin/env bash
# display information about subdomains.

domain_subdomain_func(){
	local domain="$1"
	local subdomain="$2"
	local record=$(dig +short -t CNAME "$subdomain.$domain" | awk 'NR==1 {print $1}')
	local destination=$(dig +short "$subdomain.$domain" | awk 'NR==1')

	if [[ -z "$record" ]]; then
		record="A"
	fi

	echo "The subdomain $subdomain is a $record record and points to $destination"
}

domain="$1"
subdomain="$2"

if [[ -n "$subdomain" ]]; then
	domain_subdomain_func "$domain" "$subdomain"
else
	sub_list="www lb-01 web-01 web-02"
	for sub_d in $sub_list; do
		domain_subdomain_func "$domain" "$sub_d"
	done
fi
