#!/usr/bin/env bash
# Installs nginx on my web-01 server
# Nginx should be listening on port 80

apt-get update

apt-get install -y nginx

echo "hello world" /var/www/html/index.html

service nginx restart
