#!/usr/bin/env bash
# Installs nginx on my web-01 server
# Nginx should be listening on port 80

apt-get update

apt-get install -y nginx

sed -i 's/^listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default

service nginx restart

echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
