#!/usr/bin/env bash
# Installs nginx on my web-01 server
# Nginx should be listening on port 80

set -e

apt-get update

apt-get install -y nginx


echo "server {
    listen 80 default server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    
    location / {
        echo "Hello World!"
    }

    location /redirect_me {
        return 301 https://www.linkedin.com/in/rahmon-adeniji-7b67a8101/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
