#!/usr/bin/env bash
# Installs nginx on my web-01 server
# Nginx should be listening on port 80

set -e

apt-get update

apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html 
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
