#!/usr/bin/env bash
# Install and configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '22 i \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
