#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy
sudo sed -i '37 a \\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back' /etc/haproxy/haproxy.cfg
sudo sed -i '44 a \\nbackend\n\tbalance roundrobin\n\tserver web-01 52.201.229.120 check\n\tserver web-02 54.146.76.101 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
