#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

dump_file="backup.sql"

mysqldump --all-databases -u root --password="$1" > "$dump_file"

date_format=$(date +"%d-%m-%Y")
compressed_file="$date_format.tar.gz"

tar -czvf "$compressed_file" "$dump_file"
