#!/usr/bin/env bash
# enable server to listen on port 80
mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default/etc/nginx/sites-enabled/default
service nginx stop
pkill nginx
service nginx start
