#!/usr/bin/env bash
# Script displays the following:
# -content of the current directory
# -files in list format
# -where only the part of the name after the first dash is displayed

for file in *; do
	if [[ ! $file == .* ]]; then
		file_name=$(echo "$file" | cut -d '-' -f2-)

		if [[ -n "$file_name" ]]; then
			echo "$file_name"
		fi
	fi
done
