#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sudo sed -i 's/localhost/127.0.0.2/' ~/hosts.new
sudo sed -i 's/facebook.com/8.8.8.8/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
