#!/usr/bin/env bash
# fix container so that Nginx is running as the nginx user.

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^listen .*/listen 8080;/g' /etc/nginx/nginx.conf

sudo service nginx restart
