#!/usr/bin/env bash
# fix container so that Nginx is running as the nginx user.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill apcahe2
sudo -u nginx service nginx start
